services:
  - type: web
    name: ai-toolkit-back
    env: node
    region: singapore
    plan: free
    buildCommand: corepack enable && corepack prepare pnpm@9.9.0 --activate && pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    # 免费版本资源限制
    scaling:
      minInstances: 1
      maxInstances: 1
    # 自动部署配置
    autoDeploy: true
